name: Security Scan

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  checkov:
    uses: clouddrove/github-shared-workflows/.github/workflows/checkov.yml@master
    with:
      directory: '.'
      continue_on_error: 'true'
      skip_check: 'CKV_TF_1,CKV_AZURE_227,CKV2_AZURE_15,CKV_AZURE_141,CKV_AZURE_226,CKV_AZURE_115,CKV_AZURE_168,CKV_AZURE_226,CKV_AZURE_232'